str = list('ATTACATCGGGCATTCGAACCTCAAGGTCGACCTGGGCATACATTTTGGCGAGAACTGTTGCAGTGTGTACGCTCCCCAACCAGAGCATGGCTCACACGTATCGAGTCGAAAACCACCGTGGGGGCGGCCGGATCCAGCGCGGACCTGCATAAAGATATTGCGGAAAATCTCCTGTGTTAGTTAACTTCAGGGCTTTTAGGGGGCTATACCGTGTCCTTCAGTCCATATTAGTCTAACCGGCTTAGGCCGCCCTCCGTTGAATGGACGTCGTCAACATTGCGAGCGGGAGAACAAGCGATTTAGGGTGTTGCTCGGTATATATATCAGTGGGCTGTTGAATTAGACTAGTTTGCGAACAATTCACAGTTCGAGGCCCCGGGGCTAGTTACCACGTGCGGTGGAACACACTTAACCACAATGCCTTTCGAATTTTATCTACGTGGCCCACGGTCCGTAAGGTCCCCAGTTTAATGGTATACTCAATCACTAGTGGCAAACAGTCGGCAGCCCCTCAGAGGCCGCGCGTAAGTTCTAAATTATCTCATTCGACGGGACTGTTTTTGGTCCCTCTCAAAATTGGGATCAGAGCACAGCAGAATTCCTAGTCCGTTGCTCTGCAAAATCAATATCTCTGGACCAAAATAGGTCTGTTTTGCTCCCCTCTATACCCAATGGGTCCGCACGGTCGGTAGATGAATGTGTATACACGAGAAGGCCGGTATCGTAAATGGATTAGGGTCACAGGGCGCGGCTGTATACGGCATACGGCATCACACCTCCTGACCCTGCTCGAATACAGTTGACTCTGGGGCGTAGAACCAGCGTATTCGCGGAGGGCCCAGAATCC')


newstr = list('')
for i in range(0,len(str)):
    if str[i] == 'A':
        str[i] = 'T'
    elif str[i] == 'T':
        str[i] =  'A'
    elif str[i] == 'C':
        str[i] =  'G'
    elif str[i] == 'G':
        str[i] =  'C'

print ("".join(str[::-1]))
